### ISSUE TITLE
Paasaa ignoring whitelist

### ISSUE THREAD

**Issue by simoncocking** [minibikini/paasaa#21]
Paasaa 0.5.0 is ignoring the supplied language whitelist:

```elixir
iex> Paasaa.detect("熊生活在森林中，不喜歡人。", whitelist: ["eng", "jpn"])
"cmn"
```

**Comment by minibikini** [comment]
Hi @simoncocking thanks for the bug report and sorry for the late response!

I just released a new version v0.5.1 with a fix.
